### PR TITLE
Fix connected REPL error handling

### LINKED ISSUE #3638: Connect external REPL seems broken in v1.91.1 (pre-release)
Using the "Connect external REPL" command in the VS Code extension on the latest pre-release version seems broken.
```julia
julia> pushfirst!(LOAD_PATH, raw"c:\Users\sebastian\.vscode\extensions\julialang.language-julia-1.91.1\scripts\packages");try using VSCodeServer; finally popfirst!(LOAD_PATH) end;VSCodeServer.serve(raw"\\.\pipe\vsc-jl-repl-9dffe9f1-a15f-438a-9925-15362975cf4d"; is_dev = "DEBUG_MODE=true" in Base.ARGS, crashreporting_pipename = raw"\\.\pipe\vsc-jl-cr-26f77b8a-bced-4b0b-bf54-0f0019139a3e");nothing # re-establishing connection with VSCode
[ Info: Precompiling VSCodeServer [9f5989ce-84fe-42d4-91ec-6a7a8d53ed0f]
ERROR: MethodError: no method matching serve(::String; is_dev::Bool, crashreporting_pipename::String)

Closest candidates are:
  serve(::Any, ::Any; is_dev, error_handler) got unsupported keyword argument "crashreporting_pipename"
   @ VSCodeServer c:\Users\sebastian\.vscode\extensions\julialang.language-julia-1.91.1\scripts\packages\VSCodeServer\src\VSCodeServer.jl:109

Stacktrace:
 [1] top-level scope
   @ REPL[1]:1
```

I'm using julia 1.10
```julia
julia> versioninfo()
Julia Version 1.10.4
Commit 48d4fd4843 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
```

### PR DESCRIPTION
**Pull request by davidanthoff**
Fixes #3638.

### CODE REVIEW

File: scripts/terminalserver/load_vscodeserver.jl [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+            Base.set_active_project(version_specific_env_path)
+        end
+    end
+    deactivate_env = () -> begin
+        @static if VERSION < v"1.8.0"
+            Base.ACTIVE_PROJECT[] = prev_proj_path
+        else
+            Base.set_active_project(prev_proj_path)
+        end
+    end
```
Comment (pfitzseb) [inline scripts/terminalserver/load_vscodeserver.jl:22]: I've made two changes here:
1. The active env is now restored to `prev_proj_path`
2. `Base.ACTIVE_PROJECT[]` is used on Julia <1.8 to set the env
