### PR TITLE
if string comparison in @test fails, show as diff

### LINKED ISSUE #3121: Use diff UI feature for failed tests

### PR DESCRIPTION
**Pull request by brychcy**
Fixes #3121.

### CODE REVIEW

File: scripts/packages/VSCodeTestServer/src/VSCodeTestServer.jl [hunk 1]
```diff
@@ -169,6 +169,33 @@ function run_testitem_handler(conn, params::TestserverRunTestitemRequestParams)
...
+                if m !== nothing
+                    expected = unescape_string(m.captures[1])
+                    actual = unescape_string(m.captures[2])
+                    return (expected, actual)
+                end
+            end
+        end
+    catch err
+        # if anything goes wrong (e.g. unescaping failed), just return nothing (meaning no diff will be shown)
+    end
```
Comment (davidanthoff) [inline scripts/packages/VSCodeTestServer/src/VSCodeTestServer.jl:195]: I'm generally not a fan of try catch blocks that blanket hide errors, I think I would prefer that we just fail if things go wrong, and then hopefully telemetry will tell us about it and we can fix it? Unless this is handling a specific failure mode that you know about, but in that case I think we should also try to handle that more narrowly.

**Review by davidanthoff — CHANGES_REQUESTED** [review]
This is great, thanks so much!

I have one small request for a change.

We eventually need to port this change over to https://github.com/julia-vscode/TestItemServer.jl, I'm in the middle of moving the current code here in the julia-vscode repo over into that separate repo, but I can handle that once we have merged this here, so feel free to ignore.

File: scripts/packages/VSCodeTestServer/src/VSCodeTestServer.jl (hunk 1 above)
Comment (brychcy) [reply scripts/packages/VSCodeTestServer/src/VSCodeTestServer.jl:197]: I wasn't sure if  result.data exists in older julia versions, but I've now checked, and it exists at least since 1.0.

the only thing that could happen is what is already mentioned in the comment: unescaping might fail if the user registers a weird failure result, e.g.
@testitem "#bad_escape" begin
    Test.record(Test.get_testset(), Test.Fail(:test,"" , "\"\\,\" == \"\"", false, LineNumberNode(2, @__FILE__)))
end

I've pushed an updated commit that narrow the try...catch to those unescape statements.

**Review by davidanthoff — APPROVED** [review]
Excellent, thanks so much :)
