### PR TITLE
fix repl again

### LINKED ISSUE #1328: `@macroexpand` ignored in Julia REPL
Julia 1.4.2, vscode-insider 0.16.3, either in the REPL or inline mode, it seems to completley ignore the presence of `@macroexpand`:

```julia
julia> @macroexpand @time 1
  0.000000 seconds
1
```

Guessing its just inadvertantly eval'ing the output of macros which return an expression, here's another version of this bug where you should be getting the expression `:(1+2)` but vscode is evaluating it, 

```julia
julia> macro return_expr()
           :(:(1+2))
       end
@return_expr (macro with 1 method)

julia> @return_expr
3
```

### PR DESCRIPTION
**Pull request by aviatesk**
fixes #1328 by wrapping evaluation in our own functions (i.e. `evalrepl`)
accompanied with:
- cutting off internal calls from stacktrace
- use `include_string` and more graceful stack trace

and I've found the same kind of error can happen for `Main.ans` update, so fixed it as well.

### CODE REVIEW

File: scripts/packages/VSCodeServer/src/repl.jl [hunk 1]
```diff
@@ -59,6 +59,56 @@ function hideprompt(f)
...
+end
+
+function display_parse_error(io, err::Meta.ParseError)
+  printstyled(io, "ERROR: "; bold = true, color = Base.error_color())
+  printstyled(io, "syntax: ", err.msg; color = Base.error_color())
+  println(io)
+end
+
+# don't inline this so we can find it in the stacktrace
+@noinline repleval(m, code, file) = include_string(m, code, file)
```
Comment (pfitzseb) [inline scripts/packages/VSCodeServer/src/repl.jl:101]: Why `include_string` over [`eval`](https://github.com/JunoLab/Atom.jl/blob/master/src/repl.jl#L196)?

Comment (pfitzseb) [reply scripts/packages/VSCodeServer/src/repl.jl:101]: So we don't have to parse in an extra step. Not sure if I like it, but we can iterate on this in a follow-up.

Comment (aviatesk) [reply scripts/packages/VSCodeServer/src/repl.jl:101]: another benefit is we can specify `file` within `include_string` so that stacktrace shows `REPL[exec_cnt]` as a location, without fixing `Core.LineNumber`s in `Expr`.
And I don't see the downside of using it ? Not too sure about that though.

Comment (pfitzseb) [reply scripts/packages/VSCodeServer/src/repl.jl:101]: The only slightly annoying thing about this is that everything's wrapped in a `LoadError`:
image

Comment (pfitzseb) [reply scripts/packages/VSCodeServer/src/repl.jl:101]: Fixed by https://github.com/julia-vscode/julia-vscode/pull/1331.
